INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('1', 'super_admin.html', 'Dashboard', '', 'main_url', '1', '1', '1');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('2', 'student_info/registration.html', 'Registration', '', 'main_url', '2', '1', '2');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('5', 'subject_panel/sub.html', 'Subject', '', 'main_url', '3', '1', '5');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('6', 'result_show/result.html', 'Class Result', '', 'main_url', '6', '1', '6');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('7', 'super_admin/class_reg.html', 'Class Promoted', '', 'main_url', '7', '1', '7');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('8', 'attendant_panel/attendant.html', 'Attendant', '', 'main_url', '8', '1', '8');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('9', 'pdf_panel/pdf_show.html', 'PDF Report', '', 'main_url', '9', '1', '9');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('10', 'url_panel/url.html', 'URL', '', 'main_url', '10', '1', '10');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('11', 'baton_panel/baton.html', 'Baton', '', 'main_url', '11', '1', '11');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('12', 'super_admin/option.html', 'Option Input', '', 'main_url', '12', '1', '12');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('13', 'super_admin/view_option.html', 'View Option', '', 'main_url', '13', '1', '13');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('14', 'gallery/input_img.html', 'Input Gallery', '', 'main_url', '14', '1', '14');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('15', 'gallery/view.html', 'View Gallery', '', 'main_url', '15', '1', '15');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('16', 'attendant_panel/attendant_assigned.html', 'Attendant Assigned', 'fa fa-asterisk fa-4x', 'attendant', '8', '1', '16');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('17', 'attendant_panel/attendant_input.html', 'Attendant Input', 'fa fa-renren fa-4x', 'attendant', '8', '1', '17');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('18', 'attendant_panel/report_month.html', 'Monthly Report', 'fa fa-refresh fa-spin fa-4x fa-fw', 'attendant', '8', '1', '18');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('19', 'pdf_panel/id_card.html', 'ID Card Front', 'fa fa-inr fa-4x', 'pdf', '9', '1', '19');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('20', 'pdf_panel/id_card_back.html', 'ID Card Back', 'fa fa-info fa-4x', 'pdf', '9', '1', '20');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('21', 'pdf_panel/id_card_back_border.html', 'ID Card Back Without Border', 'fa fa-ils fa-4x', 'pdf', '9', '1', '21');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('22', 'pdf_panel/site_list.html', 'Site List', 'fa fa-gears fa-4x', 'pdf', '9', '1', '22');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('23', 'pdf_panel/result.html', 'Result Transcript', 'fa fa-magic fa-4x', 'pdf', '9', '1', '23');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('25', 'pdf_panel/transfer_input.html', 'TRANSFER CERTIFICATE INPUT', 'fa fa-bullseye fa-4x', 'pdf', '9', '1', '25');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('26', 'url_panel/url_in.html', 'Url Input', 'fa fa-user-md fa-4x', 'url', '10', '1', '26');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('27', 'url_panel/url_group.html', 'Url Group Input', 'fa fa-user-secret fa-4x', 'url', '10', '1', '27');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('28', 'url_panel/url_view.html', 'Url View', 'fa fa-vimeo fa-4x', 'url', '10', '1', '28');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('29', 'student_info/student_reg.html', 'Student Registration', 'fa fa-user fa-4x', 'registration', '2', '1', '29');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('30', 'student_info/student_view.html', 'Student View', 'fa fa-vimeo fa-4x', 'registration', '2', '1', '30');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('31', 'subject_panel/update_reg_info.html', 'Update Student Registration', 'fa fa-random fa-4x', 'registration', '2', '1', '31');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('32', 'super_admin/teacher_reg.html', 'Teacher Registration', 'fa fa-user-times fa-4x', 'registration', '2', '1', '32');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('33', 'super_admin/view_teacher.html', 'Teacher View', 'fa fa-vimeo fa-4x', 'registration', '2', '1', '33');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('34', 'baton_panel/baton_input.html', 'Baton Input', 'fa fa-male fa-4x', 'baton', '11', '1', '34');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('35', 'sms_panel/sms.html', 'SMS', '', 'main_url', '16', '1', '35');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('36', 'sms_panel/attendant_absent.html', 'Attendant Absent', 'fa fa-smile-o fa-4x', 'sms', '16', '1', '36');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('37', 'add_four_panel/search_subject.html', 'Select Remove And Four Subject', 'fa fa-image fa-4x', 'subject', '3', '1', '37');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('38', 'subject_panel/subject.html', 'Subject Input', 'fa fa-indent fa-4x', 'subject', '3', '1', '38');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('39', 'subject_panel/subject_assigned.html', 'Subject Assigned', 'fa fa-info fa-4x', 'subject', '3', '1', '39');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('40', 'student_info/stu_reg_xls.html', 'Student Registration By Excel', 'fa fa-registered fa-4x', 'registration', '2', '1', '40');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('41', 'pdf_panel/transfer.html', 'TRANSFER CERTIFICATE', 'fa fa-jpy fa-4x', 'pdf', '9', '1', '41');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('42', 'pdf_panel/admid_card.html', 'Admid Card', 'fa fa-vimeo fa-4x', 'pdf', '9', '1', '42');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('43', 'pdf_panel/prottayan.html', 'Prottayan', 'fa fa-gears fa-4x', 'pdf', '9', '1', '43');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('44', 'pdf_panel/all_class_report.html', 'Class Result', 'fa fa-i-cursor fa-4x', 'pdf', '9', '1', '44');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('45', 'pdf_panel/testimonial_input.html', 'Testimonial Input', 'fa fa-hand-spock-o fa-4x', 'pdf', '9', '1', '45');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('46', 'pdf_panel/testimonial.html', 'Testimonial', 'fa fa-hand-scissors-o fa-4x', 'pdf', '9', '1', '46');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('47', 'pdf_panel/class_report.html', 'Class Report', 'fa fa-vimeo fa-4x', 'pdf', '9', '1', '47');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('48', 'profile_panel/user_admin.html', 'Profile', '', 'main_url', '17', '1', '48');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('49', 'sms_panel/attendant_absent_all_class.html', 'Attendant Absent All Class', 'fa fa-bullseye fa-4x', 'sms', '16', '1', '49');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('50', 'sms_panel/absent_all_class.html', 'Absent Class', 'fa fa-vimeo fa-4x', 'sms', '16', '1', '50');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('51', 'baton_panel/baton_assign.html', 'Baton Assign', 'fa fa-exchange fa-4x', 'baton', '11', '1', '51');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('52', 'baton_panel/baton_report.html', 'Baton Report', 'fa fa-pie-chart fa-4x', 'baton', '11', '1', '52');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('53', 'baton_panel/top_sheet.html', 'Top Sheet', 'fa fa-refresh fa-spin fa-4x fa-fw', 'baton', '11', '1', '53');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('54', 'attendant_panel/report_month_teacher.html', 'Monthly Report Teacher', 'fa fa-ils fa-4x', 'attendant', '8', '1', '54');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('55', 'notice_panel/notice.html', 'Notice', '', 'main_url', '18', '1', '55');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('56', 'sms_panel/result_sms.html', 'Result SMS', 'fa fa-ils fa-4x', 'sms', '16', '1', '56');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('57', 'student_info/student_info.html', 'Student Information', 'fa fa-bullseye fa-4x', 'registration', '2', '1', '57');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('58', 'pdf_panel/student_info.html', 'Student Info', 'fa fa-user fa-4x', 'pdf', '9', '1', '58');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('59', 'baton_panel/baton_package.html', 'Baton Package', 'fa fa-file-archive-o fa-4x', 'baton', '11', '1', '59');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('60', 'baton_panel/baton_set_package.html', 'Baton Set Package', 'fa fa-puzzle-piece fa-4x', 'baton', '11', '1', '60');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('61', 'baton_panel/baton_input_new.html', 'Baton Input New Std', 'fa fa-male fa-4x', 'baton', '11', '1', '61');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('62', 'setting_panel/setting.html', 'Setting', '', 'main_url', '19', '1', '62');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('63', 'setting_panel/academy_information.html', 'Academy Information', 'fa fa-ils fa-4x', 'setting', '19', '1', '1');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('64', 'machine_attendant_panel/machine.html', 'Machine Attendant', '', 'main_url', '20', '1', '64');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('65', 'machine_attendant_panel/machine_absent.html', 'Absent', 'fa fa-file-archive-o fa-4x', 'machine', '20', '1', '65');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('66', 'machine_attendant_panel/machine_report_month.html', 'Monthly Report', 'fa fa-ils fa-4x', 'machine', '20', '1', '66');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('67', 'machine_attendant_panel/holly_day.html', 'Holly Day', 'fa fa-gears fa-4x', 'machine', '20', '1', '67');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('68', 'machine_attendant_panel/machine_absent_all_class.html', 'Absent All Class', 'fa fa-file-archive-o fa-4x', 'machine', '20', '1', '68');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('69', 'machine_attendant_panel/machine_yearly_report.html', 'Yearly Report', 'fa fa-leaf fa-4x', 'machine', '20', '1', '69');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('70', 'baton_panel/baton_invoice.html', 'Payment Invoice', 'fa fa-exchange fa-4x', 'baton', '11', '1', '70');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('71', 'invoice_panel/generate_invoice.html', 'Generate Invoice', 'fa fa-file-text fa-4x', 'invoice', '21', '1', '5');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('72', 'invoice_panel/invoice.html', 'Invoice', '', 'main_url', '21', '1', '74');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('73', 'invoice_panel/invoice_set_package.html', 'Payment Set Package', 'fa fa-puzzle-piece fa-4x', 'invoice', '21', '1', '2');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('74', 'invoice_panel/invoice_package.html', 'Payment Package', 'fa fa-file-archive-o fa-4x', 'invoice', '21', '1', '1');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('75', 'invoice_panel/invoice_create.html', 'Invoice Create', 'fa fa-plus-circle fa-4x', 'invoice', '21', '1', '6');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('76', 'invoice_panel/invoice_print.html', 'Invoice Print', 'fa fa-print fa-4x', 'invoice', '21', '1', '7');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('77', 'invoice_panel/invoice_report.html', 'Invoice Report', 'fa fa-bar-chart fa-4x', 'invoice', '21', '1', '8');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('78', 'invoice_panel/top_sheet.html', 'Top Sheet', 'fa fa-refresh fa-spin fa-4x fa-fw', 'invoice', '21', '1', '9');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('79', 'admit_card_panel/admit_card_page.html', 'Admit Card', '', 'main_url', '22', '1', '79');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('80', 'admit_card_panel/admit_card.html', 'Admit Card View', 'fa fa-file-archive-o fa-4x', 'admit_card', '22', '1', '80');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('81', 'admit_card_panel/exam_date.html', 'Exam Date', 'fa fa-plus fa-4x', 'admit_card', '22', '1', '81');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('82', 'profile_panel/change_password.html', 'Change Password', 'fa fa fa-key fa-4x', 'profile', '17', '1', '82');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('83', 'invoice_panel/previous_due.html', 'Previous Due Entry', 'fa fa-hourglass-half fa-4x fa-fw', 'invoice', '21', '1', '3');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('84', 'baton_panel/baton_due.html', 'Due Student', 'fa fa fa-money fa-4x', 'baton', '11', '1', '84');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('85', 'invoice_panel/advance_pay.html', 'Advance Pay', 'fa fa-filter fa-4x', 'invoice', '21', '1', '4');
INSERT INTO tbl_url (`url_id`, `url_name`, `url_title`, `url_icon`, `url_type`, `url_active`, `status`, `order_by`) VALUES ('86', 'setting_panel/backup.html', 'Backup', 'fa fa-hdd-o fa-4x', 'setting', '19', '1', '2');
#
# TABLE STRUCTURE FOR: tbl_url_authentication
#

DROP TABLE IF EXISTS tbl_url_authentication;

CREATE TABLE `tbl_url_authentication` (
  `url_group_name` varchar(100) NOT NULL,
  `url_id` int NOT NULL,
  `url_insert` int NOT NULL DEFAULT '0',
  `url_edit` int NOT NULL DEFAULT '0',
  `url_delete` int NOT NULL DEFAULT '0',
  `url_authentication_id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`url_authentication_id`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8mb3;

#
# TABLE DATA FOR: tbl_url_authentication
#

INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '1', '1', '1', '1', '2');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '2', '1', '1', '1', '3');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '38', '1', '1', '1', '4');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '39', '1', '1', '1', '6');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '5', '1', '1', '1', '10');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '7', '1', '1', '1', '12');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '8', '1', '1', '1', '13');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '9', '1', '1', '1', '14');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '10', '1', '1', '1', '15');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '11', '1', '1', '1', '16');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '12', '1', '1', '1', '17');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '13', '1', '1', '1', '18');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '14', '1', '1', '1', '19');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '15', '1', '1', '1', '20');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '16', '1', '1', '1', '21');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '17', '1', '1', '1', '22');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '18', '1', '1', '1', '23');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '19', '1', '1', '1', '24');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '20', '1', '1', '1', '25');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '21', '1', '1', '1', '26');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '22', '1', '1', '1', '27');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '23', '1', '1', '1', '28');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '25', '1', '1', '1', '30');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '26', '1', '1', '1', '31');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '27', '1', '1', '1', '32');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '28', '1', '1', '1', '33');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '29', '1', '1', '1', '34');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '30', '1', '1', '1', '35');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '31', '1', '1', '1', '36');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '32', '1', '1', '1', '37');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '33', '1', '1', '1', '38');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '34', '1', '1', '1', '43');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '35', '1', '1', '1', '44');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '36', '1', '1', '1', '45');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '37', '1', '1', '1', '46');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '1', '1', '1', '1', '47');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '11', '1', '1', '1', '49');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '34', '1', '1', '1', '52');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '40', '1', '1', '1', '53');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '41', '1', '1', '1', '54');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '42', '1', '1', '1', '55');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '43', '1', '1', '1', '56');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '44', '1', '1', '1', '57');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '45', '1', '1', '1', '58');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '46', '1', '1', '1', '59');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '47', '1', '1', '1', '60');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '48', '1', '1', '1', '61');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '49', '1', '1', '1', '62');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '50', '1', '1', '1', '63');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '51', '1', '1', '1', '64');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '52', '1', '1', '1', '65');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '24', '1', '1', '1', '66');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '53', '1', '1', '1', '67');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '54', '1', '1', '1', '68');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '52', '1', '1', '1', '70');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '53', '1', '1', '1', '71');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '55', '1', '1', '1', '72');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '56', '1', '1', '1', '123');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '58', '1', '1', '1', '125');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '1', '1', '1', '1', '126');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '2', '1', '1', '1', '127');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '18', '1', '1', '1', '128');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '29', '1', '1', '1', '129');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '30', '1', '1', '1', '130');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '9', '1', '1', '1', '131');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '44', '1', '1', '1', '132');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '5', '1', '1', '0', '133');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '6', '1', '1', '0', '134');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '7', '0', '0', '0', '135');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '8', '1', '1', '0', '136');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '9', '1', '1', '0', '137');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '10', '0', '0', '0', '138');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '11', '1', '1', '0', '139');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '12', '0', '0', '0', '140');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '13', '0', '0', '0', '141');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '14', '1', '1', '0', '142');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '15', '1', '1', '0', '143');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '16', '1', '1', '0', '144');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '17', '1', '1', '0', '145');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '19', '0', '0', '0', '146');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '20', '0', '0', '0', '147');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '21', '0', '0', '0', '148');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '22', '1', '1', '0', '149');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '23', '1', '1', '0', '150');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '25', '1', '1', '0', '151');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '26', '0', '0', '0', '152');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '27', '0', '0', '0', '153');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '28', '0', '0', '0', '154');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '31', '1', '1', '0', '155');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '32', '1', '1', '0', '156');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '33', '1', '1', '0', '157');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '34', '1', '1', '0', '158');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '35', '1', '1', '0', '159');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '36', '1', '1', '0', '160');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '37', '1', '1', '0', '161');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '38', '0', '0', '0', '162');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '39', '1', '1', '0', '163');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '40', '0', '0', '0', '164');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '41', '1', '1', '0', '165');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '42', '1', '1', '0', '166');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '43', '1', '1', '0', '167');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '44', '1', '1', '0', '168');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '45', '1', '1', '0', '169');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '46', '1', '1', '0', '170');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '47', '1', '1', '0', '171');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '48', '0', '0', '0', '172');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '49', '1', '1', '0', '173');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '50', '1', '1', '0', '174');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '51', '1', '1', '0', '175');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '52', '1', '1', '0', '176');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '53', '1', '1', '0', '177');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '54', '1', '1', '0', '178');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '55', '1', '1', '0', '179');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '56', '1', '1', '0', '180');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '57', '1', '1', '0', '181');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '58', '1', '1', '0', '182');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('admin', '59', '1', '1', '1', '183');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '59', '1', '1', '1', '184');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '60', '1', '1', '1', '185');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '61', '1', '1', '1', '186');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '62', '1', '1', '1', '187');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '63', '1', '1', '1', '188');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '64', '1', '1', '1', '189');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '65', '1', '1', '1', '190');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '66', '1', '1', '1', '191');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '67', '1', '1', '1', '192');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '68', '1', '1', '1', '193');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '61', '1', '1', '1', '194');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '66', '1', '1', '1', '196');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('teacher', '64', '1', '1', '1', '197');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '69', '1', '1', '1', '198');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '70', '1', '1', '1', '199');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '71', '1', '1', '1', '200');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '72', '1', '1', '1', '201');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '73', '1', '1', '1', '202');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '74', '1', '1', '1', '203');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '75', '1', '1', '1', '204');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '76', '1', '1', '1', '205');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '77', '1', '1', '1', '206');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '78', '1', '1', '1', '207');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '79', '1', '1', '1', '208');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '80', '1', '1', '1', '209');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '81', '1', '1', '1', '210');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '82', '1', '1', '1', '211');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '29', '1', '1', '1', '212');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '30', '1', '1', '1', '213');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '32', '1', '1', '1', '214');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '33', '1', '1', '1', '215');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '40', '1', '1', '1', '216');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '5', '1', '1', '1', '217');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '37', '1', '1', '1', '218');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '38', '1', '1', '1', '219');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('sub_admin', '39', '1', '1', '1', '220');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '83', '1', '1', '1', '221');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '84', '1', '1', '1', '222');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '72', '1', '1', '1', '223');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '71', '1', '1', '1', '224');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '73', '1', '1', '1', '225');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '74', '1', '1', '1', '226');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '75', '1', '1', '1', '227');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '76', '1', '1', '1', '228');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '77', '1', '1', '1', '229');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '78', '1', '1', '1', '230');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('baton', '83', '1', '1', '1', '231');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '85', '1', '1', '1', '232');
INSERT INTO tbl_url_authentication (`url_group_name`, `url_id`, `url_insert`, `url_edit`, `url_delete`, `url_authentication_id`) VALUES ('super_admin', '86', '1', '1', '1', '233');
